[project]
name = "dsview"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "thibaultdu", email = "39222414+thibaultdu@users.noreply.github.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.6",
    "langchain>=0.3.11",
    "langchain-community>=0.3.11",
    "langchain-experimental>=0.3.3",
    "langchain-openai>=0.2.12",
    "levenshtein>=0.26.1",
    "mlflow>=2.19.0",
    "numpy>=1.26.4",
    "obsidiantools>=0.10.0",
    "omegaconf>=2.3.0",
    "pandas>=2.2.3",
    "pydantic>=2.10.3",
    "pypdf>=5.1.0",
    "python-dotenv>=1.0.1",
    "python-frontmatter>=1.1.0",
    "pyyaml>=6.0.2",
    "rich>=13.9.4",
    "sqlmodel>=0.0.22",
    "streamlit>=1.41.1",
    "tiktoken>=0.8.0",
    "typer>=0.15.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
