configs:
  - model_type: DEFAULT
    model_config:
      chat_model: mistral-small-latest
      embedding_model: mistral-embed
      provider: MISTRAL
      token_limit: 100000
  - model_type: SEMANTIC_SCORE
    model_config:
      chat_model: smollm2:1.7b
      embedding_model: all-minilm:latest
      provider: OLLAMA
      token_limit: 8192
