tags: 
  - "Machine Learning"
  - "Deep Learning"
  - "AutoML"
  - "Cloud Computing"
  - "Statistics"
  - "Mathematics"
  - "Model Deployment"
  - "MlOps"
  - "Data Engineering"
  - "Data Visualization"
  - "DevOps"
  - "Python"
  - "Large Language Model"
  - "Natural Language Processing"
  - "Generative AI"
  - "Time Series"
  - "Graph (networks)"
  - "Computer Vision"
  - "Supervised Learning"
  - "Unsupervised Learning"
  - "Semi-supervised Learning"
  - "Active Learning"
  - "AI regulation"
  - "Data Quality"
  - "Model evaluation"
subjects:
  - "Organization"
  - "AI Company"
  - "Model"
  - "Python library"
