import json
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from dataclasses import dataclass
from datetime import date
from typing import Annotated, Optional

from mcp.server.fastmcp import Context, FastMCP
from mcp.server.session import ServerSession
from pydantic import BaseModel, Field
from sqlmodel import Session

from dsview.config import load_extraction_config
from dsview.db import engine
from dsview.db.query import ExtractionIndex, TopicsIndex
from dsview.db.schemas import ExtractionResult, ExtractionTopic, InputContent

# TODO maybe should handle async calls ?

extraction_config = load_extraction_config()


@dataclass
class AppContext:
    db_session: Session
    extraction_index: ExtractionIndex
    topics_index: TopicsIndex


# ? Why async
@asynccontextmanager
async def app_lifespan(server: FastMCP) -> AsyncIterator[AppContext]:
    """Manage application lifecycle with type-safe context."""
    # Initialize on startup
    db_session = Session(engine)
    extraction_index = ExtractionIndex()
    topics_index = TopicsIndex()

    extraction_index.build()
    topics_index.build()

    try:
        yield AppContext(
            db_session=db_session,
            extraction_index=extraction_index,
            topics_index=topics_index,
        )
    finally:
        # Cleanup on shutdown
        db_session.close()
        extraction_index.close()
        topics_index.close()


mcp = FastMCP(
    "DSview mcp server",
    lifespan=app_lifespan,
    host="0.0.0.0",
    port=8000,
    instructions="""
        Provide tools for exploring a dsview vault, a custom
        Data Science knowledge database managed by the user. It contains a curated
        list of **contents** (research papers, online courses, blog
        posts, github repositories, ...) and **topics** that are
        extracted from them (Machine Learning concepts,
        Development tools, libraries, ...).

        The database is structured as a graph of contents linked
        to topics. It allows to navigate the knowlegde graph and
        explore adjacent information.

        This is intented to be used in order to help the user
        remind of relevant information about a subject or
        help them during the ideation phase of a new project /
        task.

        Most times, this server will first be used to search
        content or topics (based on fuzzy and semantic search), which
        translates to finding a relevant nodes within the graph.
        And then exploring their neighbors.
    """,
    stateless_http=True,
    json_response=True,
)


# @mcp.resource("stats://graph")
# def get_graph_stats() -> str:

#     return """
#         Number of contents :
#         Number of topics :
#         Total number of nodes :
#         Total number of edges :
#     """


class DsviewContent(BaseModel):
    id: int = Field(
        description="Unique id of the content, also referenced as content_id"
    )
    link: str = Field(description="Content url")
    upload_date: date = Field(description="Date of content upload by the user")
    already_read: bool = Field(
        description="Wether or not the user have already read the content"
    )
    read_priority: int = Field(
        description="If the content has not been read, gives a priority rating"
    )
    relevance: int = Field(
        description="If the content has been read, rating from the user on how relevant the content is"
    )
    source: Optional[str] = Field(
        default=None, description="Source where the user found the content"
    )
    title: Optional[str] = Field(
        default=None,
        description="Title automatically detected by dsview, None if extraction failed",
    )
    type: Optional[str] = Field(
        default=None,
        description="Content type infered by dsview, None if extraction failed",
    )
    tags: Optional[list[str]] = Field(
        default=None,
        description="Content tags infered by dsview, None if extraction failed",
    )
    summary: Optional[str] = Field(
        default=None,
        description="Content summary generated by dsview, None if extraction failed",
    )


@mcp.tool()
def get_content_topics(
    content_id: int, ctx: Context[ServerSession, AppContext]
) -> DsviewContent:
    """Retrieve a stored content from its id"""

    db_session = ctx.request_context.lifespan_context.db_session

    input_content = db_session.get(InputContent, content_id)

    if input_content is None:
        raise ValueError(f"Content id {content_id} was not found in database")

    dsview_content = DsviewContent(**input_content.model_dump())

    extraction_result = db_session.get(ExtractionResult, content_id)

    if extraction_result is not None:
        dsview_content.title = extraction_result.title
        dsview_content.type = extraction_result.content_type
        dsview_content.tags = [tag.name for tag in extraction_result.tags]
        dsview_content.summary = extraction_result.summary

    return dsview_content


class DsviewContentList(BaseModel):
    contents: list[DsviewContent]


@mcp.tool()
def get_connected_contents(
    topic_id: int,
    ctx: Context[ServerSession, AppContext],
) -> DsviewContentList:
    db_session = ctx.request_context.lifespan_context.db_session

    topic = db_session.get(ExtractionTopic, topic_id)

    contents = []
    for extraction_result in topic.extractions:
        input_content = db_session.get(InputContent, extraction_result.content_id)
        dsview_content = DsviewContent(**input_content.model_dump())
        dsview_content.title = extraction_result.title
        dsview_content.type = extraction_result.content_type
        dsview_content.tags = [tag.name for tag in extraction_result.tags]
        dsview_content.summary = extraction_result.summary
        contents.append(dsview_content)

    return DsviewContentList(contents=contents)


@mcp.resource("config://content_types")
def get_content_types() -> str:
    """Retrieve all possible content types"""
    types = list(extraction_config.content_types.values())
    return json.dumps(types)


# ! I don't know if type value or keys are stored in db
@mcp.tool()
def search_content(
    search_term: str,
    ctx: Context[ServerSession, AppContext],
    limit: int = 10,
    types: Annotated[Optional[list[str]], "Filter content by types"] = None,
) -> DsviewContentList:
    """
    Search contents that are most closely related to the search term.
    It is performed using semantic and fuzzy search on the title and
    summary of contents within the database. This is one of the two
    entrypoints in the knowledge graph.
    """

    db_session = ctx.request_context.lifespan_context.db_session
    extraction_index = ctx.request_context.lifespan_context.extraction_index

    filters = (
        ["content_type IN ('" + "','".join(types) + "')"] if types is not None else None
    )

    result = extraction_index.query_with_rff(search_term, limit, filters=filters)

    contents = []

    for content_id, row in result.iterrows():
        input_content = db_session.get(InputContent, content_id)
        dsview_content = DsviewContent(**input_content.model_dump())
        dsview_content.title = row["title"]
        dsview_content.summary = row["summary"]

        contents.append(dsview_content)

    return DsviewContentList(contents=contents)


class DsviewTopic(BaseModel):
    id: int
    type: str
    name: str
    description: str


class DsviewTopicList(BaseModel):
    topics: list[DsviewTopic]


@mcp.resource("config://topic_types")
def get_topic_types() -> str:
    """Retrieve all possible topic types"""
    types = list(extraction_config.topic_categories.values())
    return json.dumps(types)


@mcp.tool()
def get_connected_topics(
    content_id: str,
    ctx: Context[ServerSession, AppContext],
) -> DsviewTopicList:

    db_session = ctx.request_context.lifespan_context.db_session

    extraction_result = db_session.get(ExtractionResult, content_id)

    topics = []

    for topic in extraction_result.topics:
        topics.append(DsviewTopic(**topic.model_dump(exclude=["embedding"])))

    return DsviewTopicList(topics=topics)


@mcp.tool()
def search_topic(
    search_term: str,
    ctx: Context[ServerSession, AppContext],
    limit: int = 10,
    types: Annotated[Optional[list[str]], "The type of topic to search for"] = None,
) -> DsviewTopicList:
    """
    Search for topics in the knowledge graph.
    """

    db_session = ctx.request_context.lifespan_context.db_session
    topics_index = ctx.request_context.lifespan_context.topics_index

    filters = ["type IN ('" + "','".join(types) + "')"] if types is not None else None

    result = topics_index.query_with_rff(search_term, limit, filters=filters)

    topics = []

    for topic_id, row in result.iterrows():
        topic = db_session.get(ExtractionTopic, topic_id)
        dsview_topic = DsviewTopic(**topic.model_dump(exclude=["embedding"]))

        topics.append(dsview_topic)

    return DsviewTopicList(topics=topics)


if __name__ == "__main__":
    mcp.run(transport="streamable-http")
