apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsview
  labels:
    app: dsview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dsview
  template:
    metadata:
      labels:
        app: dsview
    spec:
      serviceAccountName: dsview-sa
      containers:
      - name: dsview-deploy
        image: ghcr.io/tdurouchoux/dsview:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 8501
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
            scheme: HTTP
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
            scheme: HTTP
          timeoutSeconds: 1
        resources:
          requests:
            memory: "1000Mi"
            cpu: "1000m"
          limits:
            memory: "8000Mi"
            cpu: "4000m"
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: dsview-secret
              key: OPENAI_API_KEY
        - name: VAULT_REPOSITORY
          valueFrom:
            secretKeyRef:
              name: dsview-secret
              key: VAULT_REPOSITORY
        - name: GITHUB_USERNAME
          valueFrom:
            secretKeyRef:
              name: dsview-secret
              key: GITHUB_USERNAME
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: dsview-secret
              key: GITHUB_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: dsview-service
  labels:
    app: dsview
spec:
  selector:
    app: dsview
  ports:
  - name: dsview-ingest
    protocol: TCP
    port: 8000
    targetPort: 8000
  - name: dsview-label
    protocol: TCP
    port: 8501
    targetPort: 8501
  type: ClusterIP
